// <auto-generated />
namespace tiplessCashJar.repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingAbandon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingAbandon));
        
        string IMigrationMetadata.Id
        {
            get { return "201606050135037_addingAbandon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
